# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Cquantile <- function(x, q) {
    .Call('_GSFA_Cquantile', PACKAGE = 'GSFA', x, q)
}

mvrnormArma <- function(mu, sigma) {
    .Call('_GSFA_mvrnormArma', PACKAGE = 'GSFA', mu, sigma)
}

sample_Z_cpp <- function(N, K, Y, F, W, G, beta, psi) {
    .Call('_GSFA_sample_Z_cpp', PACKAGE = 'GSFA', N, K, Y, F, W, G, beta, psi)
}

sample_gammaBeta_cpp <- function(N, M, K, Z, G, Gamma, beta, sigma_b2, pi_beta) {
    .Call('_GSFA_sample_gammaBeta_cpp', PACKAGE = 'GSFA', N, M, K, Z, G, Gamma, beta, sigma_b2, pi_beta)
}

sample_W_cpp <- function(P, K, Y, Z, F, W, psi, sigma_w2, c2) {
    .Call('_GSFA_sample_W_cpp', PACKAGE = 'GSFA', P, K, Y, Z, F, W, psi, sigma_w2, c2)
}

sample_F_cpp <- function(P, K, W, pi_vec, sigma_w2, c2) {
    .Call('_GSFA_sample_F_cpp', PACKAGE = 'GSFA', P, K, W, pi_vec, sigma_w2, c2)
}

sample_FW_spike_slab_cpp <- function(N, P, K, Y, Z, F, W, psi, sigma_w2, pi_vec) {
    .Call('_GSFA_sample_FW_spike_slab_cpp', PACKAGE = 'GSFA', N, P, K, Y, Z, F, W, psi, sigma_w2, pi_vec)
}

sample_psi_cpp <- function(N, P, Y, Z, F, W, prior_psi) {
    .Call('_GSFA_sample_psi_cpp', PACKAGE = 'GSFA', N, P, Y, Z, F, W, prior_psi)
}

sample_pi_cpp <- function(P, K, F, prior_pi) {
    .Call('_GSFA_sample_pi_cpp', PACKAGE = 'GSFA', P, K, F, prior_pi)
}

sample_pi_beta_cpp <- function(M, K, Gamma, prior_pibeta) {
    .Call('_GSFA_sample_pi_beta_cpp', PACKAGE = 'GSFA', M, K, Gamma, prior_pibeta)
}

sample_sigma_w2_cpp <- function(K, P, F, W, prior_sigma2w, c2) {
    .Call('_GSFA_sample_sigma_w2_cpp', PACKAGE = 'GSFA', K, P, F, W, prior_sigma2w, c2)
}

sample_sigma_w2_spike_slab_cpp <- function(K, F, W, prior_sigma2w) {
    .Call('_GSFA_sample_sigma_w2_spike_slab_cpp', PACKAGE = 'GSFA', K, F, W, prior_sigma2w)
}

sample_c2_cpp <- function(K, P, F, W, sigma2w, prior_c) {
    .Call('_GSFA_sample_c2_cpp', PACKAGE = 'GSFA', K, P, F, W, sigma2w, prior_c)
}

sample_sigma_b2_cpp <- function(M, Gamma, beta, prior_sigma2b) {
    .Call('_GSFA_sample_sigma_b2_cpp', PACKAGE = 'GSFA', M, Gamma, beta, prior_sigma2b)
}

initialize_random <- function(K, Y) {
    .Call('_GSFA_initialize_random', PACKAGE = 'GSFA', K, Y)
}

initialize_svd <- function(K, Y) {
    .Call('_GSFA_initialize_svd', PACKAGE = 'GSFA', K, Y)
}

initialize_given_Z <- function(K, Y, init_Z) {
    .Call('_GSFA_initialize_given_Z', PACKAGE = 'GSFA', K, Y, init_Z)
}

compute_posterior_mean_cpp <- function(Gamma_mtx, beta_mtx, pi_beta_mtx, Z_mtx, F_mtx, W_mtx, pi_mtx, sigma_w2_mtx, c2_mtx, niter = 200L, ave_niter = 100L, prior_type = "mixture_normal") {
    .Call('_GSFA_compute_posterior_mean_cpp', PACKAGE = 'GSFA', Gamma_mtx, beta_mtx, pi_beta_mtx, Z_mtx, F_mtx, W_mtx, pi_mtx, sigma_w2_mtx, c2_mtx, niter, ave_niter, prior_type)
}

compute_lfsr_cpp <- function(beta_mtx, W_mtx, F_mtx, use_niter = 100L, prior_type = "mixture_normal") {
    .Call('_GSFA_compute_lfsr_cpp', PACKAGE = 'GSFA', beta_mtx, W_mtx, F_mtx, use_niter, prior_type)
}

gsfa_gibbs_cpp <- function(Y, G, K, prior_type = "mixture_normal", initialize = "svd", Z_given = NULL, prior_s = 50, prior_r = 0.2, prior_sb = 20, prior_rb = 0.2, prior_gp = 1, prior_hp = 1, prior_gb = 1, prior_hb = 1, prior_gw = 1, prior_hw = 1, prior_gc = 3, prior_hc = 0.5, niter = 500L, ave_niter = 200L, lfsr_niter = 200L, verbose = TRUE, return_samples = TRUE) {
    .Call('_GSFA_gsfa_gibbs_cpp', PACKAGE = 'GSFA', Y, G, K, prior_type, initialize, Z_given, prior_s, prior_r, prior_sb, prior_rb, prior_gp, prior_hp, prior_gb, prior_hb, prior_gw, prior_hw, prior_gc, prior_hc, niter, ave_niter, lfsr_niter, verbose, return_samples)
}

restart_gsfa_gibbs_cpp <- function(Y, G, Z, F, W, Gamma, beta, pi_vec, pi_beta, psi, sigma_w2, sigma_b2, c2, prior_params, prior_type = "mixture_normal", niter = 500L, ave_niter = 200L, lfsr_niter = 200L, verbose = TRUE, return_samples = TRUE) {
    .Call('_GSFA_restart_gsfa_gibbs_cpp', PACKAGE = 'GSFA', Y, G, Z, F, W, Gamma, beta, pi_vec, pi_beta, psi, sigma_w2, sigma_b2, c2, prior_params, prior_type, niter, ave_niter, lfsr_niter, verbose, return_samples)
}

